version: '3'

services:

  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443

  react:
    build: ./demo
    container_name: react-app
    expose:
      - "3000"
    ports:
      - 3000:3000